version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health_database
    ports:
      - "3307:3306"  # El puerto local 3307 mapea al puerto 3306 del contenedor
    networks:
      - app-network

  app:
    build: .
    container_name: mads-todolist-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/health_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

