version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health_database
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql  # <- Agregamos persistencia de datos
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3



  app:
    build: .
    container_name: mads-todolist-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/health_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
volumes:
  mysql_data:

